import {
  type SimpleIcon,
  siAngular,
  siBitcoin,
  siDjango,
  siDocker,
  siFastapi,
  siFirebase,
  siFlutter,
  siGit,
  siGo,
  siGodotengine,
  siGooglecloud,
  siJavascript,
  siNextdotjs,
  siNodedotjs,
  siOpenjdk,
  siPostgresql,
  siPrisma,
  siPython,
  siReact,
  siRedis,
  siRust,
  siSpringboot,
  siSqlite,
  siTailwindcss,
  siTypescript,
} from 'simple-icons'

// Marquee items are free text in the CMS; known names get a logo, anything
// else renders as text only.
const icons: Record<string, SimpleIcon> = {
  angular: siAngular,
  bitcoin: siBitcoin,
  'bitcoin lightning': siBitcoin,
  django: siDjango,
  docker: siDocker,
  fastapi: siFastapi,
  firebase: siFirebase,
  flutter: siFlutter,
  gcp: siGooglecloud,
  git: siGit,
  go: siGo,
  golang: siGo,
  godot: siGodotengine,
  'google cloud': siGooglecloud,
  java: siOpenjdk,
  javascript: siJavascript,
  'next.js': siNextdotjs,
  nextjs: siNextdotjs,
  'node.js': siNodedotjs,
  nodejs: siNodedotjs,
  postgresql: siPostgresql,
  postgres: siPostgresql,
  prisma: siPrisma,
  python: siPython,
  react: siReact,
  redis: siRedis,
  rust: siRust,
  'spring boot': siSpringboot,
  sqlite: siSqlite,
  tailwind: siTailwindcss,
  'tailwind css': siTailwindcss,
  typescript: siTypescript,
}

export function techIcon(name: string): SimpleIcon | undefined {
  return icons[name.trim().toLowerCase()]
}
